queue: 'Hosted VS2017'
steps:

  # INSTALL
  - task: Npm@1
    inputs:
      workingDir: '$(PackageDirectory)'
      command: install

  # BUILD
  - task: Npm@1
    inputs:
      workingDir: '$(PackageDirectory)'
      command: custom
      customCommand: 'run build'

  # TEST
  - task: Npm@1
    inputs:
      workingDir: '$(PackageDirectory)'
      command: custom
      customCommand: 'test -- --reporter mocha-junit-reporter'

  # PUBLISH TEST RESULTS
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**\*.xml'
      searchFolder: '$(Common.TestResultsDirectory)'
      mergeTestResults: true
    condition: succeededOrFailed()

  # SEMANTIC RELEASE
  - script: npx semantic-release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  # PUBLISH NPM
  # - task: Npm@1
  #   inputs:
  #     workingDir: '$(PackageDirectory)'
  #     command: publish
  #     publishEndpoint: chstone
  #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
