queue: 'Hosted VS2017'
steps:

  # INSTALL
  - task: Npm@1
    inputs:
      workingDir: '$(PackageDirectory)'
      command: install

  # BUILD
  - task: Npm@1
    inputs:
      workingDir: '$(PackageDirectory)'
      command: custom
      customCommand: 'run build'

  # TEST
  - task: Npm@1
    inputs:
      workingDir: '$(PackageDirectory)'
      command: custom
      customCommand: 'test -- --reporter mocha-junit-reporter'

  # PUBLISH TEST RESULTS
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**\*.xml'
      searchFolder: '$(Common.TestResultsDirectory)'
      mergeTestResults: true
    condition: succeededOrFailed()

  # PUBLISH NPM
  - task: Npm@1
    inputs:
      command: publish
      workingDir: '$(Build.StagingDirectory)'
      publishRegistry: useFeed
      publishFeed: '115d3c38-cd52-41d6-8fda-16dd326a56c9'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
